### ISSUE TITLE
Review #1 - Detalles en el ingreso + persistencia de la page.

### ISSUE THREAD

**Issue by FacundoEG** [MaxiJ16/piedra-papel-tijera-v2#1]
Hola Maxi! como estas? sabes que estuve probando un poco la webapp y tengo algunas cositas minimas que me gustaría señalarte!

Las voy a dividir en dos cosas:

1. El juego funciona muy bien en lineas generales, pero noto que te deja acceder con mas de dos usuarios registrados a una misma sala. Por ejemplo, el usuario Facundo creo esta sala y jugo con Juancin, pero despues cree al usuario Raulsiño y me dejo entrar a la sala, generando que los 3 esten adentro, Facundo y Juancin pudieron jugar pero Raulsiño se queda esperando:
![Screenshot_20220123_094210](https://user-images.githubusercontent.com/79592789/150678936-732c4b42-d252-4671-bd03-c33f1fd33474.png)

Acordate que una de las premisas de este desafío es que cuando ya hayan dos usuarios registrados en una sala y/o conectados no te permita ingresar, mas que nada para que no haya esta clase de problemas.

2. Otro detalle que note, pero mas a modo de arquitectura, es que te cuando recargas la pagina vuelve a renderizar todo y a cargar el state que estaba en el SessionStorage, pero fijate que los usuarios no se vuelven a conectar a la rtdb y cuando vos tocas "jugar", cambia el estado pero el otro jugador no se entera y se quedan esperando.
![Screenshot_20220123_095032](https://user-images.githubusercontent.com/79592789/150679202-233697b4-34cb-41e6-8ad5-5ab818e31cbd.png)

Para resolver esto facilmente, te recomiendo que cuando vuelvas a cargar el state al volver a renderizar, tambien vuelvas a conectar a los usuarios asi reciben la data actualizada de la RTBD.

Igual no te preocupes, no son errores muy grandes, la webapp en si funciona muy fluida y esta bastante optimizada! te diría que arregles eso a modo de sugerencia pero de mi parte te voy a dar el visto bueno al desafío!

Otra cosita que me gustaría sugerirte, ya que me parecio muy bueno que preguntes al principio si el user es nuevo o no, pero me da la impresión que se podrían generar algunos errores si ya volves a preguntar el nombre cuando el usuario va a crear una sala o unirse, me paso que a proposito cambie el nombre poniendo uno diferente que el que use para registrarme y no me dejaba. 

Asi que te dejo ese detalle a modo de sugerencia tambien.

Te mando un saludo grande y te deseo lo mejor para lo proximo!

**Comment by MaxiJ16** [comment]
Hola Facu, ahora voy a revisar eso que me decís y tratar de corregirlo, si después le podes dar una mirada corregido también te lo agradecería! un saludo grande para vos también, muchas gracias por las sugerencias!

**Comment by MaxiJ16** [comment]
Facu, ya pude arreglar los detalles que me señalaste, si podes volver a mirarlo buenísimo, sino te agradezco por hacerme ver esos errores

**Comment by FacundoEG** [comment]
Maxi a la noche le pego una miradita y te digo que tal si? Igual tranqui que el desafío estaba muy bien!

**Comment by FacundoEG** [comment]
Maxi ahi lo probe y quedo espectacular! te felicito por esos cambios!

Te cierro el issue porque se resolvio todo, saludos!

**Comment by MaxiJ16** [comment]
Buenísimo Facu, muchas gracias! saludos
